### PR TITLE
Added versionist

### PR DESCRIPTION
**Pull request by nazrhom**
Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
add to whitelist

**Comment by hedss** [comment]
@Page- @nazrhom Is Jenkins still used for this module, or is it now superceeded by Circle?

**Comment by nazrhom** [comment]
@hedss It is superceeded by Circle, afaik this should be true for every repo.

**Comment by hedss** [comment]
@nazrhom Thanks, I'll change the Jenkins from required to optional (I don't have the ability to disable the Jenkins build, but I'll raise an issue in the appropriate place).

**Pull request merged**
