### PR TITLE
Set up circleci auto-publishing

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by pimterry** [comment]
Code looks good, but it looks like you've set the circleci status from before you added the config as required though. That status now won't run (so will block merges), and the new node 4/6/8 statuses which do run aren't checked by versionbot.

**Comment by Page-** [comment]
I'm not 100% what you mean @pimterry, but I'm still setting up the required checks so it should be fine after that

**Comment by Page-** [comment]
Also you can't add the config as required beforehand, because you can only mark ones that have run recently as required (so they have to run first)

**Comment by pimterry** [comment]
Yes, looks good now.

The issue was that although yes, you can't set up the `ci/circleci: node-*` checks as required before you open the branch, you'd marked the existing `ci/circleci` job as required. That check was only there and running because you had enabled circleci before adding a circle config file - when you have no config, circle runs a status check with no job name (since it doesn't have one). That job would never run again now that a config is included in this PR, which leaves you with a required check that doesn't run and blocks your PRs.

Anyway, you've sorted it now, so all's well :+1:

**Comment by Page-** [comment]
Ah, yeah, I changed it at the same time I marked the new ones as required - otherwise PRs could be merged without having a build succeed

**Pull request merged**
